version: '3.4'

services:
  bizyeriz.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  bizyerizdb:
    container_name: bizyerizdb
    environment:
      - POSTGRES_DB=bizyerizdb
      - POSTGRES_USER=codi
      - POSTGRES_PASSWORD=codi4309         
    volumes:
      - postgres_bizyeriz_volume:/var/lib/postgresql/data 
    ports:
      - "5432:5432"    

