version: '3.4'

services:
  bizyeriz.webapi:
    image: ${DOCKER_REGISTR}bizyerizwebapi
    build:
      context: .
      dockerfile: src/Presentation/bizYeriz.WebApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=bizyerizdb;Username=codi;Password=postgres123
    ports:
      - "8080:8080"
    depends_on:
      yerizDb:
        condition: service_healthy
    command: ["sh", "-c", "dotnet ef database update && dotnet bizYeriz.WebApi.dll"]

  yerizDb:
    image: postgres:16
    container_name: yerizDb
    environment:
      - POSTGRES_DB=bizyerizdb
      - POSTGRES_USER=codi
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./.containers/drivers-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codi"]
      interval: 10s
      timeout: 5s
      retries: 5
