version: '3.4'

services:
  bizyeriz.webapi:
    image: bizyerizwebapi
    container_name: bizyerizwebapi
    build:
      context: .
      dockerfile: src/Presentation/bizYeriz.WebApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost,5432;Port=5432;Database=bizyerizdb;Username=codi;Password=codi4309
    ports:
      - "8080:8080"
    depends_on:
      bizyerizdb:
        condition: service_healthy
    command: ["sh", "-c", "dotnet ef database update && dotnet bizYeriz.WebApi.dll"]

  bizyerizdb:
    image: postgres:16
    container_name: bizyerizdb
    environment:
      - POSTGRES_DB=bizyerizdb
      - POSTGRES_USER=codi
      - POSTGRES_PASSWORD=codi4309
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codi"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_bizyeriz_volume:/var/lib/postgresql/data

volumes:
  postgres_bizyeriz_volume:
