version: "3.4"

services:
  bizyeriz.webapi:
    image: webapi
    build:
      context: .
      dockerfile: src/Presentation/bizYeriz.WebApi/Dockerfile
    container_name: bizyeriz_webapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - bizyeriz-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bizyeriz-network:
    driver: bridge
